### PR TITLE
Fix: Improve filter layout for mobile

### PR DESCRIPTION
**Pull request by GODrums**
### Motivation

On smaller screens (e.g. mobile) the leaderboard filters are sometimes outside of the viewing area.

### Description

This PR gives the filter component more responsiveness for smaller screens.

### Screenshots (if applicable)

Width <580px:
image
Width 580-1280px:
image

#### General

- [x] PR title is clear and descriptive
- [x] PR description explains the purpose and changes
- [x] Code follows project coding standards
- [x] Self-review of the code has been done
- [x] Changes have been tested locally
- [x] Screenshots have been attached (if applicable)
- [ ] Documentation has been updated (if applicable)

#### Client (if applicable)

- [x] UI changes look good on all screen sizes and browsers
- [x] No console errors or warnings
- [x] User experience and accessibility have been tested
- [ ] Added Storybook stories for new components
- [ ] Components follow design system guidelines (if applicable)

### CODE REVIEW

**Review by FelixTJDietrich — CHANGES_REQUESTED** [review]
Can you also make the container fit the subviews? There is a lot of whitespace to the side 🤔 
image
image

**Comment by GODrums** [comment]
> Can you also make the container fit the subviews? There is a lot of whitespace to the side 🤔

What testing setup did you use to get this whitespace? I can't seem to reproduce it at all.

**Comment by FelixTJDietrich** [comment]
Ah okay, I was just checking Storybook 🤔 Then it's fine

**Comment by FelixTJDietrich** [comment]
But it also looks kind of like this in your PR screenshot 
image

**Review by FelixTJDietrich — APPROVED** [review]

**Comment by GODrums** [comment]
> Ah okay, I was just checking Storybook 🤔 Then it's fine, but ideally it should behave similarly

So the reason why it's not limited in Storybook is because we use the Tailwind `container` to limit the max-width of our whole "page body".



> But it also looks kind of like this in your PR screenshot

The image is exactly the "wrapping" break-point from `flex-wrap`. So if you add a few pixels of width, it will snap back into the same row. Looks like this then:
image

**Pull request merged**
